CREATE TABLE IF NOT EXISTS `myaac_lua_monsters` (
	`id` int(11) NOT NULL AUTO_INCREMENT,
	`name` varchar(255) NOT NULL,
	`mana` int(11) NOT NULL DEFAULT 0,
	`exp` int(11) NOT NULL DEFAULT 0,
	`health` int(11) NOT NULL DEFAULT 0,
	`outfit` VARCHAR(255) NOT NULL DEFAULT '',
	`speed_lvl` int(11) NOT NULL default 1,
	`use_haste` tinyint(1) NOT NULL DEFAULT 0,
	`summonable` tinyint(1) NOT NULL DEFAULT 0,
	`convinceable` tinyint(1) NOT NULL DEFAULT 0,
	`rewardboss` tinyint(1) NOT NULL DEFAULT 0,
	`voices` varchar(3000) NOT NULL DEFAULT '',
	`immunities` varchar(255) NOT NULL DEFAULT '',
	`elements` varchar(1000) NOT NULL DEFAULT '',
	`defense` INT(11) NOT NULL DEFAULT '0',
	`armor` INT(11) NOT NULL DEFAULT '0',
	`race` varchar(255) NOT NULL DEFAULT '',
	`loot` varchar(10000) NOT NULL DEFAULT '',
	`summons` varchar(1000) NOT NULL DEFAULT '',
	`flags` varchar(1000) NOT NULL DEFAULT '',
	`hide` tinyint(1) NOT NULL default 0,
	PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARACTER SET=utf8mb4;
